import { Edge, Node } from '@xyflow/react';

export const initialNodes: Node[] = [
  {
    id: 'login',
    position: { x: 100, y: 50 },
    data: { label: 'User Login\n(Username/Password)' },
    style: {
      backgroundColor: 'rgba(147, 51, 234, 0.1)',
      border: '2px solid #9333ea',
      borderRadius: '12px',
      padding: '15px',
      color: '#ffffff',
      fontSize: '14px',
      fontWeight: '500',
      textAlign: 'center',
      boxShadow: '0 0 20px rgba(147, 51, 234, 0.3)',
      backdropFilter: 'blur(10px)',
    },
  },
  {
    id: 'server-auth',
    position: { x: 400, y: 50 },
    data: { label: 'Server Authentication\n& JWT Generation' },
    style: {
      backgroundColor: 'rgba(59, 130, 246, 0.1)',
      border: '2px solid #3b82f6',
      borderRadius: '12px',
      padding: '15px',
      color: '#ffffff',
      fontSize: '14px',
      fontWeight: '500',
      textAlign: 'center',
      boxShadow: '0 0 20px rgba(59, 130, 246, 0.3)',
      backdropFilter: 'blur(10px)',
    },
  },
  {
    id: 'jwt-response',
    position: { x: 700, y: 50 },
    data: { label: 'JWT Token\nReturned to Client' },
    style: {
      backgroundColor: 'rgba(20, 184, 166, 0.1)',
      border: '2px solid #14b8a6',
      borderRadius: '12px',
      padding: '15px',
      color: '#ffffff',
      fontSize: '14px',
      fontWeight: '500',
      textAlign: 'center',
      boxShadow: '0 0 20px rgba(20, 184, 166, 0.3)',
      backdropFilter: 'blur(10px)',
    },
  },
  {
    id: 'localstorage',
    position: { x: 400, y: 200 },
    data: { label: 'Store JWT in\nLocalStorage' },
    style: {
      backgroundColor: 'rgba(168, 85, 247, 0.1)',
      border: '2px solid #a855f7',
      borderRadius: '12px',
      padding: '15px',
      color: '#ffffff',
      fontSize: '14px',
      fontWeight: '500',
      textAlign: 'center',
      boxShadow: '0 0 20px rgba(168, 85, 247, 0.3)',
      backdropFilter: 'blur(10px)',
    },
  },
  {
    id: 'api-request',
    position: { x: 100, y: 350 },
    data: { label: 'Protected API\nRequest' },
    style: {
      backgroundColor: 'rgba(236, 72, 153, 0.1)',
      border: '2px solid #ec4899',
      borderRadius: '12px',
      padding: '15px',
      color: '#ffffff',
      fontSize: '14px',
      fontWeight: '500',
      textAlign: 'center',
      boxShadow: '0 0 20px rgba(236, 72, 153, 0.3)',
      backdropFilter: 'blur(10px)',
    },
  },
  {
    id: 'retrieve-jwt',
    position: { x: 400, y: 350 },
    data: { label: 'Retrieve JWT from\nLocalStorage' },
    style: {
      backgroundColor: 'rgba(168, 85, 247, 0.1)',
      border: '2px solid #a855f7',
      borderRadius: '12px',
      padding: '15px',
      color: '#ffffff',
      fontSize: '14px',
      fontWeight: '500',
      textAlign: 'center',
      boxShadow: '0 0 20px rgba(168, 85, 247, 0.3)',
      backdropFilter: 'blur(10px)',
    },
  },
  {
    id: 'auth-header',
    position: { x: 700, y: 350 },
    data: { label: 'Add JWT to\nAuthorization Header' },
    style: {
      backgroundColor: 'rgba(20, 184, 166, 0.1)',
      border: '2px solid #14b8a6',
      borderRadius: '12px',
      padding: '15px',
      color: '#ffffff',
      fontSize: '14px',
      fontWeight: '500',
      textAlign: 'center',
      boxShadow: '0 0 20px rgba(20, 184, 166, 0.3)',
      backdropFilter: 'blur(10px)',
    },
  },
  {
    id: 'server-validate',
    position: { x: 400, y: 500 },
    data: { label: 'Server Validates\nJWT Token' },
    style: {
      backgroundColor: 'rgba(59, 130, 246, 0.1)',
      border: '2px solid #3b82f6',
      borderRadius: '12px',
      padding: '15px',
      color: '#ffffff',
      fontSize: '14px',
      fontWeight: '500',
      textAlign: 'center',
      boxShadow: '0 0 20px rgba(59, 130, 246, 0.3)',
      backdropFilter: 'blur(10px)',
    },
  },
  {
    id: 'success-response',
    position: { x: 100, y: 650 },
    data: { label: 'Authorized Response\n(Success)' },
    style: {
      backgroundColor: 'rgba(34, 197, 94, 0.1)',
      border: '2px solid #22c55e',
      borderRadius: '12px',
      padding: '15px',
      color: '#ffffff',
      fontSize: '14px',
      fontWeight: '500',
      textAlign: 'center',
      boxShadow: '0 0 20px rgba(34, 197, 94, 0.3)',
      backdropFilter: 'blur(10px)',
    },
  },
  {
    id: 'token-expire',
    position: { x: 700, y: 650 },
    data: { label: 'Token Expired/Invalid\n(Redirect to Login)' },
    style: {
      backgroundColor: 'rgba(239, 68, 68, 0.1)',
      border: '2px solid #ef4444',
      borderRadius: '12px',
      padding: '15px',
      color: '#ffffff',
      fontSize: '14px',
      fontWeight: '500',
      textAlign: 'center',
      boxShadow: '0 0 20px rgba(239, 68, 68, 0.3)',
      backdropFilter: 'blur(10px)',
    },
  },
];

export const initialEdges: Edge[] = [
  {
    id: 'login-server',
    source: 'login',
    target: 'server-auth',
    label: 'POST credentials',
    style: { stroke: '#9333ea', strokeWidth: 3 },
    labelStyle: { fill: '#ffffff', fontSize: '12px', fontWeight: '500' },
    labelBgStyle: { fill: 'rgba(0, 0, 0, 0.7)', fillOpacity: 0.8 },
  },
  {
    id: 'server-jwt',
    source: 'server-auth',
    target: 'jwt-response',
    label: 'Generate JWT',
    style: { stroke: '#3b82f6', strokeWidth: 3 },
    labelStyle: { fill: '#ffffff', fontSize: '12px', fontWeight: '500' },
    labelBgStyle: { fill: 'rgba(0, 0, 0, 0.7)', fillOpacity: 0.8 },
  },
  {
    id: 'jwt-storage',
    source: 'jwt-response',
    target: 'localstorage',
    label: 'Store token',
    style: { stroke: '#14b8a6', strokeWidth: 3 },
    labelStyle: { fill: '#ffffff', fontSize: '12px', fontWeight: '500' },
    labelBgStyle: { fill: 'rgba(0, 0, 0, 0.7)', fillOpacity: 0.8 },
  },
  {
    id: 'api-retrieve',
    source: 'api-request',
    target: 'retrieve-jwt',
    label: 'Get token',
    style: { stroke: '#ec4899', strokeWidth: 3 },
    labelStyle: { fill: '#ffffff', fontSize: '12px', fontWeight: '500' },
    labelBgStyle: { fill: 'rgba(0, 0, 0, 0.7)', fillOpacity: 0.8 },
  },
  {
    id: 'retrieve-header',
    source: 'retrieve-jwt',
    target: 'auth-header',
    label: 'Attach token',
    style: { stroke: '#a855f7', strokeWidth: 3 },
    labelStyle: { fill: '#ffffff', fontSize: '12px', fontWeight: '500' },
    labelBgStyle: { fill: 'rgba(0, 0, 0, 0.7)', fillOpacity: 0.8 },
  },
  {
    id: 'header-validate',
    source: 'auth-header',
    target: 'server-validate',
    label: 'Send request',
    style: { stroke: '#14b8a6', strokeWidth: 3 },
    labelStyle: { fill: '#ffffff', fontSize: '12px', fontWeight: '500' },
    labelBgStyle: { fill: 'rgba(0, 0, 0, 0.7)', fillOpacity: 0.8 },
  },
  {
    id: 'validate-success',
    source: 'server-validate',
    target: 'success-response',
    label: 'Valid token',
    style: { stroke: '#22c55e', strokeWidth: 3 },
    labelStyle: { fill: '#ffffff', fontSize: '12px', fontWeight: '500' },
    labelBgStyle: { fill: 'rgba(0, 0, 0, 0.7)', fillOpacity: 0.8 },
  },
  {
    id: 'validate-expire',
    source: 'server-validate',
    target: 'token-expire',
    label: 'Invalid token',
    style: { stroke: '#ef4444', strokeWidth: 3 },
    labelStyle: { fill: '#ffffff', fontSize: '12px', fontWeight: '500' },
    labelBgStyle: { fill: 'rgba(0, 0, 0, 0.7)', fillOpacity: 0.8 },
  },
];
